#!/usr/bin/env python3
"""Deterministic cc-rpi component rendering (Python 3.11+, standard library).

The manifest owns component identity and selection; adapters own native fields.
Authored skill headers support plain identifier names and JSON-quoted string
scalars only. This is deliberately not a general YAML parser. Custom installed
files are never parsed as authoring inputs or regenerated by this renderer.
"""
import argparse
import fnmatch
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import re
import shlex
import sys

HARNESSES = ("claude", "codex")
PORTABLE_FIELDS = {"name", "description", "license", "compatibility"}
KINDS = {"skill", "rule", "instruction", "hook", "config", "resource"}
CLAUDE_FIELDS = {"argument-hint", "disable-model-invocation", "user-invocable"}


def safe_path(root, relative):
    if not isinstance(relative, str) or not relative:
        raise ValueError("component paths must be nonempty strings")
    path = Path(relative)
    if path.is_absolute() or ".." in path.parts or path.as_posix() != relative:
        raise ValueError("path escapes source/output: " + relative)
    full = root / path
    try:
        full.resolve().relative_to(root.resolve())
    except ValueError as error:
        raise ValueError("symlink escapes source/output: " + relative) from error
    return full


def parse_skill(path):
    content = path.read_bytes()
    if not content.startswith(b"---\n") or b"\n---\n" not in content[4:]:
        raise ValueError(f"{path}: missing portable frontmatter delimiters")
    header, body = content[4:].split(b"\n---\n", 1)
    metadata = {}
    for line in header.decode("utf-8").splitlines():
        match = re.fullmatch(r"([a-z][a-z-]*): (.+)", line)
        if not match:
            raise ValueError(f"{path}: unsupported portable header syntax: {line!r}")
        key, scalar = match.groups()
        if key not in PORTABLE_FIELDS or key in metadata:
            raise ValueError(f"{path}: unsupported or duplicate portable field: {key}")
        if key == "name" and re.fullmatch(r"[a-z0-9-]{1,64}", scalar):
            value = scalar
        else:
            try:
                value = json.loads(scalar)
            except json.JSONDecodeError as error:
                raise ValueError(f"{path}: {key} must be a JSON-quoted string") from error
        if not isinstance(value, str) or not value or "\n" in value:
            raise ValueError(f"{path}: {key} must be a nonempty single-line string")
        metadata[key] = value
    if not re.fullmatch(r"[a-z0-9-]{1,64}", metadata.get("name", "")):
        raise ValueError(f"{path}: invalid skill name")
    if not metadata.get("description") or len(metadata["description"]) > 1024:
        raise ValueError(f"{path}: description missing or exceeds 1024 characters")
    if not body.strip() or len(body.splitlines()) > 500:
        raise ValueError(f"{path}: body must contain 1..500 lines")
    return metadata, body


def strip_frontmatter(content):
    if content.startswith(b"---\n"):
        try:
            return content[4:].split(b"\n---\n", 1)[1]
        except IndexError as error:
            raise ValueError("unterminated rule frontmatter") from error
    return content


def resource_pairs(root, component):
    directory = safe_path(root, component["source"])
    pairs = []
    destinations = set()
    for resource in component.get("resources", []):
        if isinstance(resource, str):
            source, destination = safe_path(directory, resource), resource
        elif isinstance(resource, dict) and set(resource) == {"source", "destination"}:
            source, destination = safe_path(root, resource["source"]), resource["destination"]
        else:
            raise ValueError(f"{component['id']}: invalid resource declaration")
        # Destinations describe the new skill tree. A canonical symlink may
        # point to a shared authoring source outside this skill directory.
        safe_path(Path("/virtual-output"), destination)
        if destination == "SKILL.md" or destination in destinations or not source.is_file():
            raise ValueError(f"{component['id']}: missing or duplicate resource {destination}")
        destinations.add(destination)
        pairs.append((source, destination))
    return pairs


def load_manifest(root):
    root = Path(root).resolve()
    manifest = json.loads((root / "templates/distribution.json").read_text())
    if manifest.get("schema_version") != 1 or not manifest.get("components"):
        raise ValueError("unsupported or empty distribution manifest")
    if not re.fullmatch(r"\d+\.\d+\.\d+", manifest.get("version", "")):
        raise ValueError("manifest version must use major.minor.patch")
    budget = manifest.get("managed_root_budget_bytes")
    if not isinstance(budget, int) or isinstance(budget, bool) or not 0 < budget <= 8192:
        raise ValueError("managed root budget must be 1..8192 bytes")
    ids, names = set(), set()
    for component in manifest["components"]:
        cid = component.get("id")
        if not isinstance(cid, str) or not re.fullmatch(r"[a-z]+:[a-z0-9-]+", cid) or cid in ids:
            raise ValueError(f"duplicate or invalid component ID: {cid}")
        ids.add(cid)
        if component.get("kind") not in KINDS:
            raise ValueError(f"{cid}: unsupported component kind")
        if component.get("scope") not in ("user", "project") or component.get("selection") not in ("default", "optional"):
            raise ValueError(f"{cid}: missing scope or selection")
        harnesses = component.get("harnesses")
        if not isinstance(harnesses, list) or not harnesses or len(set(harnesses)) != len(harnesses) or set(harnesses) - set(HARNESSES):
            raise ValueError(f"{cid}: invalid harness coverage")
        source = safe_path(root, component.get("source"))
        if not source.exists():
            raise ValueError(f"{cid}: missing source {source}")
        if component["kind"] == "skill":
            entrypoint = safe_path(root, component["source"] + "/SKILL.md")
            metadata, body = parse_skill(entrypoint)
            name = component.get("name")
            if name != metadata["name"] or name != source.name or name in names:
                raise ValueError(f"{cid}: duplicate/mismatched skill identity")
            names.add(name)
            if component.get("category") not in ("workflow", "domain", "helper"):
                raise ValueError(f"{cid}: invalid skill category")
            if component.get("ownership") != {"direct": "cc-rpi", "plugin": "native-manager"}:
                raise ValueError(f"{cid}: skills require direct/plugin ownership distinction")
            pairs = resource_pairs(root, component)
            declared = {p.resolve() for p, _ in pairs}
            for resource, destination in pairs:
                alias = safe_path(root, component["source"] + "/" + destination)
                if alias.is_file() and not alias.is_symlink():
                    if alias.read_bytes() != resource.read_bytes():
                        raise ValueError(f"{cid}: bundled resource alias differs: {destination}")
                    declared.add(alias.resolve())
            actual = {p.resolve() for p in source.rglob("*") if p.is_file() and p != entrypoint and "__pycache__" not in p.parts}
            if actual - declared:
                raise ValueError(f"{cid}: undeclared bundled resource: {actual - declared}")
            for _, destination in pairs:
                if destination.encode() not in body:
                    raise ValueError(f"{cid}: resource not reachable from skill body: {destination}")
            for alias in component.get("aliases", []):
                if not re.fullmatch(r"[a-z0-9-]+", alias):
                    raise ValueError(f"{cid}: invalid alias")
            if not isinstance(component.get("explicit_only"), bool):
                raise ValueError(f"{cid}: explicit_only must be boolean")
        elif component["kind"] == "rule":
            mapping = component.get("mapping", {})
            if mapping.get("mode") not in ("universal", "conditional"):
                raise ValueError(f"{cid}: missing rule mapping")
            if mapping["mode"] == "conditional" and (not mapping.get("paths") or not mapping.get("tasks")):
                raise ValueError(f"{cid}: conditional rules need path and task mappings")
        elif component["kind"] in ("hook", "config", "resource"):
            for harness in harnesses:
                safe_path(root, component.get("outputs", {}).get(harness))
        if not isinstance(component.get("dependencies"), list):
            raise ValueError(f"{cid}: dependencies must be explicit")
    components = {component["id"]: component for component in manifest["components"]}
    authored_skills = {str(path.parent.relative_to(root)) for directory in ("templates/skills", ".codex/skills")
                       for path in (root / directory).glob("*/SKILL.md")}
    declared_skills = {c["source"] for c in components.values() if c["kind"] == "skill"}
    if authored_skills != declared_skills:
        raise ValueError("manifest skill coverage mismatch: " + str(authored_skills ^ declared_skills))
    authored_rules = {str(path.relative_to(root)) for path in (root / "templates/rules").glob("*.md")}
    declared_rules = {c["source"] for c in components.values() if c["kind"] == "rule"}
    if authored_rules != declared_rules:
        raise ValueError("manifest rule coverage mismatch: " + str(authored_rules ^ declared_rules))
    def visit(cid, ancestors):
        if cid in ancestors:
            raise ValueError("component dependency cycle: " + cid)
        for dependency in components[cid]["dependencies"]:
            if dependency not in ids:
                raise ValueError(f"{cid}: missing dependency {dependency}")
            visit(dependency, ancestors | {cid})
    for cid in ids:
        visit(cid, set())
    for consolidation in manifest.get("consolidations", []):
        if consolidation.get("into") not in ids or not consolidation.get("reason"):
            raise ValueError("invalid rule consolidation")
    return manifest


def load_adapter(root, harness):
    adapter = json.loads((root / f"templates/adapters/{harness}.json").read_text())
    allowed = {"schema_version", "harness", "preamble", "frontmatter", "explicit_field", "sidecar", "component_overrides"}
    if set(adapter) - allowed or adapter.get("schema_version") != 1 or adapter.get("harness") != harness:
        raise ValueError("unsupported adapter schema: " + harness)
    fields = adapter.get("frontmatter", {})
    if not isinstance(fields, dict) or (set(fields) - CLAUDE_FIELDS if harness == "claude" else fields):
        raise ValueError("unsupported native fields in " + harness + " adapter")
    overrides = adapter.get("component_overrides", {})
    if not isinstance(overrides, dict) or (harness == "codex" and overrides):
        raise ValueError("unsupported adapter component overrides")
    for values in overrides.values():
        if not isinstance(values, dict) or set(values) - CLAUDE_FIELDS:
            raise ValueError("unsupported Claude component override")
    for values in [fields, *overrides.values()]:
        for key, value in values.items():
            expected = str if key == "argument-hint" else bool
            if not isinstance(value, expected):
                raise ValueError(f"{harness}: {key} requires {expected.__name__}")
    if not isinstance(adapter.get("preamble"), str):
        raise ValueError("adapter preamble must be a literal string")
    if harness == "codex" and (adapter.get("preamble") or adapter.get("sidecar") != "agents/openai.yaml" or adapter.get("explicit_field") != "policy.allow_implicit_invocation"):
        raise ValueError("Codex adapter must use supported sidecar policy and unchanged request")
    if harness == "claude" and adapter.get("explicit_field") != "disable-model-invocation":
        raise ValueError("Claude adapter requires explicit invocation control")
    return adapter


def classify_alias(name):
    return "retired" if name in ("plan", "status") else "legacy-only"


def validate_registrations(registrations):
    seen = set()
    for registration in registrations:
        identity = (registration["id"], registration["harness"])
        if identity in seen:
            raise ValueError("duplicate plugin/direct or user/project registration: " + str(identity))
        if registration.get("route") not in ("plugin", "direct") or registration.get("scope") not in ("user", "project"):
            raise ValueError("invalid registration route/scope")
        seen.add(identity)


def applicable_rules(manifest, path, task=""):
    return [component["id"] for component in manifest["components"]
            if component["kind"] == "rule" and
            (component["mapping"]["mode"] == "universal" or
             any(fnmatch.fnmatch(path, pattern) or fnmatch.fnmatch(path, pattern.removeprefix("**/"))
                 for pattern in component["mapping"]["paths"]) or
             any(trigger.lower() in task.lower() for trigger in component["mapping"]["tasks"]))]


def selected_components(manifest, domains=None):
    components = {c["id"]: c for c in manifest["components"]}
    known_domains = {c["name"] for c in components.values() if c.get("category") == "domain"}
    if domains is not None and set(domains) - known_domains:
        raise ValueError("unknown domain selection: " + str(set(domains) - known_domains))
    selected = {cid for cid, c in components.items()
                if c.get("category") != "domain" or domains is None or c["name"] in domains}
    pending = list(selected)
    while pending:
        for dependency in components[pending.pop()]["dependencies"]:
            if dependency not in selected:
                selected.add(dependency)
                pending.append(dependency)
    return [components[cid] for cid in sorted(selected)]


def native_skill(metadata, body, adapter, component):
    fields = dict(metadata)
    if adapter["harness"] == "claude":
        if component["category"] == "workflow":
            fields.update(adapter["frontmatter"])
        fields.update(adapter.get("component_overrides", {}).get(component["id"], {}))
        if component["explicit_only"]:
            fields["disable-model-invocation"] = True
    header = "---\n" + "".join(f"{key}: {json.dumps(value, ensure_ascii=False)}\n" for key, value in fields.items()) + "---\n"
    preamble = adapter["preamble"] if component["category"] == "workflow" else ""
    return header.encode() + preamble.encode() + body


def marked_block(cid, body):
    name = cid.split(":", 1)[1]
    return f"<!-- rpi:{name}:start -->\n".encode() + body.strip() + f"\n<!-- rpi:{name}:end -->\n".encode()


def render_tree(root, harnesses=HARNESSES, domains=None, include_runtime=True):
    root = Path(root).resolve()
    manifest = load_manifest(root)
    if not harnesses or set(harnesses) - set(HARNESSES):
        raise ValueError("nonempty supported harness selection required")
    components = selected_components(manifest, domains)
    tree = {}
    def emit(name, data):
        safe_path(Path("/virtual-output"), name)
        if name in tree:
            raise ValueError("duplicate generated output: " + name)
        tree[name] = data
    for harness in harnesses:
        adapter = load_adapter(root, harness)
        blocks = []
        for component in components:
            if harness not in component["harnesses"]:
                continue
            source = safe_path(root, component["source"])
            kind = component["kind"]
            if kind == "skill":
                metadata, body = parse_skill(source / "SKILL.md")
                prefix = f"{harness}/skills/{component['name']}/"
                emit(prefix + "SKILL.md", native_skill(metadata, body, adapter, component))
                for resource, destination in resource_pairs(root, component):
                    emit(prefix + destination, resource.read_bytes())
                if harness == "codex":
                    value = "false" if component["explicit_only"] else "true"
                    emit(prefix + adapter["sidecar"], f"policy:\n  allow_implicit_invocation: {value}\n".encode())
            elif kind == "rule":
                emit(f"{harness}/rules/{source.name}", source.read_bytes())
                if component["mapping"]["mode"] == "universal":
                    blocks.append(marked_block(component["id"], strip_frontmatter(source.read_bytes())))
            elif kind == "instruction":
                body = source.read_bytes()
                if re.search(rb"(?:^|\s)@(?:\./)?(?:CLAUDE|AGENTS)\.md\b", body):
                    raise ValueError("shared instruction import cycle")
                blocks.append(marked_block(component["id"], body))
            else:
                emit(harness + "/" + component["outputs"][harness], source.read_bytes())
        agents = b"\n".join(blocks)
        if not agents or len(agents) > manifest["managed_root_budget_bytes"]:
            raise ValueError(f"{harness}: managed root is {len(agents)} bytes; limit {manifest['managed_root_budget_bytes']}")
        for component in components:
            if component["kind"] == "rule" and component["mapping"]["mode"] == "conditional":
                if Path(component["source"]).name.encode() not in agents:
                    raise ValueError(f"{component['id']}: missing root rule-map reachability")
        emit(harness + "/AGENTS.md", agents)
    if not any("/SKILL.md" in name for name in tree):
        raise ValueError("rendered zero skills")
    if include_runtime and "codex" in harnesses and manifest.get("runtime_sources"):
        package = load_sibling("rpi-package")
        for name, data in package.bundle_sources(root, manifest).items():
            emit("codex/runtime/" + name, data)
    return dict(sorted(tree.items()))


def file_inventory(tree):
    return {name: {"sha256": hashlib.sha256(data).hexdigest(), "bytes": len(data)}
            for name, data in tree.items()}


def write_tree(tree, output):
    output = Path(output).absolute()
    if output.is_symlink():
        raise ValueError("generated output root must not be a symlink")
    receipt = output / "distribution-inventory.json"
    if receipt.is_symlink():
        raise ValueError("generated receipt must not be a symlink")
    previous = json.loads(receipt.read_text()) if receipt.exists() else {}
    if not isinstance(previous, dict):
        raise ValueError("invalid generated receipt")
    # Preflight every preimage and parent before touching any generated bytes.
    for name in set(previous) | set(tree):
        path = safe_path(output, name)
        current = path
        while current != output:
            if current.is_symlink():
                raise ValueError("generated output must not traverse a symlink: " + name)
            current = current.parent
        if name in previous:
            record = previous[name]
            if (not isinstance(record, dict) or not path.is_file() or
                    hashlib.sha256(path.read_bytes()).hexdigest() != record.get("sha256")):
                raise ValueError("generated preimage changed; preserve before replacing: " + name)
        elif path.exists() and (not path.is_file() or path.read_bytes() != tree[name]):
            raise ValueError("unowned output collision: " + name)
    for name in set(previous) - set(tree):
        (output / name).unlink()
    for name, data in tree.items():
        path = safe_path(output, name)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
    receipt.write_text(json.dumps(file_inventory(tree), indent=2, sort_keys=True) + "\n")


def check_tree(tree, output):
    output = Path(output)
    actual = {str(path.relative_to(output)) for path in output.rglob("*") if path.is_file() and path.name != "distribution-inventory.json" and "__pycache__" not in path.parts}
    errors = [name for name, data in tree.items() if not (output / name).is_file() or (output / name).read_bytes() != data]
    errors.extend(sorted(actual - set(tree)))
    receipt = output / "distribution-inventory.json"
    if not receipt.is_file() or json.loads(receipt.read_text()) != file_inventory(tree):
        errors.append("distribution-inventory.json")
    if errors:
        raise ValueError("generated drift: " + ", ".join(errors))


def counts(manifest):
    return {**{category: sum(c.get("category") == category for c in manifest["components"])
               for category in ("workflow", "domain", "helper")},
            "rule": sum(c["kind"] == "rule" for c in manifest["components"])}


def check_native(tree):
    # A genuine YAML consumer checks emitted native documents independently
    # from the strict authored-header parser. Rendering itself remains stdlib.
    import yaml
    checked = 0
    for name, data in tree.items():
        if re.fullmatch(r"(?:claude|codex)/skills/[^/]+/SKILL\.md", name):
            header = data[4:].split(b"\n---\n", 1)[0]
            metadata = yaml.safe_load(header)
            harness = name.split("/", 1)[0]
            allowed = PORTABLE_FIELDS | (CLAUDE_FIELDS if harness == "claude" else set())
            if not isinstance(metadata, dict) or set(metadata) - allowed:
                raise ValueError("invalid emitted native metadata: " + name)
            for key in ("name", "description"):
                if not isinstance(metadata.get(key), str) or not metadata[key]:
                    raise ValueError("missing emitted native identity: " + name)
            checked += 1
        elif re.fullmatch(r"codex/skills/[^/]+/agents/openai\.yaml", name):
            sidecar = yaml.safe_load(data)
            if (not isinstance(sidecar, dict) or set(sidecar) != {"policy"} or
                    not isinstance(sidecar["policy"], dict) or set(sidecar["policy"]) != {"allow_implicit_invocation"} or
                    not isinstance(sidecar["policy"]["allow_implicit_invocation"], bool)):
                raise ValueError("invalid emitted Codex sidecar: " + name)
            checked += 1
    if not checked:
        raise ValueError("zero native metadata documents inspected")
    return checked


def check_local_skills(directories, excluded=()):
    import yaml
    checked = 0
    for directory in directories:
        for path in Path(directory).glob("*/SKILL.md"):
            if path.parent.name in excluded:
                continue
            content = path.read_bytes()
            if not content.startswith(b"---\n") or b"\n---\n" not in content[4:]:
                raise ValueError("local skill missing header: " + str(path))
            header, body = content[4:].split(b"\n---\n", 1)
            metadata = yaml.safe_load(header)
            if (not isinstance(metadata, dict) or metadata.get("name") != path.parent.name or
                    not re.fullmatch(r"[a-z0-9-]{1,64}", metadata["name"]) or
                    not isinstance(metadata.get("description"), str) or
                    not 0 < len(metadata["description"]) <= 1024 or len(body.splitlines()) > 500):
                raise ValueError("invalid local skill identity/description/size: " + str(path))
            for reference in (path.parent / "references").glob("*.md"):
                if reference.name.encode() not in body:
                    raise ValueError("unreachable local skill reference: " + str(reference))
            checked += 1
    return checked


def check_self(root, manifest):
    selection = manifest.get("self_application", {})
    domains = selection.get("domains", [])
    tree = render_tree(root, domains=domains)
    managed = [c for c in manifest["components"] if c["kind"] == "skill"]
    selected = {c["id"] for c in selected_components(manifest, domains)}
    checked = 0
    for harness in HARNESSES:
        route = selection.get(harness)
        if route not in ("direct", "plugin"):
            raise ValueError("self-application requires an explicit route for " + harness)
        directory = root / (".claude/skills" if harness == "claude" else ".agents/skills")
        for component in managed:
            destination = directory / component["name"]
            expected = (route == "direct" and component["id"] in selected and
                        harness in component["harnesses"] and component["scope"] == "project")
            if not expected:
                if destination.exists() or destination.is_symlink():
                    raise ValueError("duplicate or unselected managed registration: " + str(destination))
                continue
            prefix = harness + "/skills/" + component["name"] + "/"
            expected_files = {name[len(prefix):]: data for name, data in tree.items() if name.startswith(prefix)}
            for name, data in expected_files.items():
                path = destination / name
                if not path.is_file() or path.read_bytes() != data:
                    raise ValueError("managed self-application drift: " + str(path))
                checked += 1
            actual = {str(p.relative_to(destination)) for p in destination.rglob("*") if p.is_file() and "__pycache__" not in p.parts}
            if actual != set(expected_files):
                raise ValueError("unexpected files in managed self-application: " + str(destination))
    agents = (root / "AGENTS.md").read_bytes()
    if agents.count(tree["codex/AGENTS.md"]) != 1:
        raise ValueError("root AGENTS managed policy/rule blocks drift")
    if re.search(rb"(?:^|\s)@(?:\./)?CLAUDE\.md\b", agents):
        raise ValueError("root AGENTS creates a reverse instruction import")
    claude = (root / "CLAUDE.md").read_text()
    if not re.search(r"^@AGENTS\.md$", claude, re.M):
        raise ValueError("CLAUDE.md must import shared AGENTS.md")
    for component in manifest["components"]:
        if component["kind"] != "rule":
            continue
        source = root / component["source"]
        installed = root / ".rpi/rules" / source.name
        if not installed.is_file() or installed.read_bytes() != source.read_bytes():
            raise ValueError("installed shared rule resource drift: " + str(installed))
        native = root / ".claude/rules" / source.name
        if component["mapping"]["mode"] == "conditional":
            if not native.is_file() or native.read_bytes() != source.read_bytes():
                raise ValueError("native conditional rule drift: " + str(native))
        elif native.exists() or native.is_symlink():
            raise ValueError("universal rule duplicated in native always-loaded rules: " + str(native))
    configuration = load_sibling("rpi-config")
    for component in selected_components(manifest, domains):
        if component["kind"] in ("hook", "resource") and component["scope"] == "project":
            for harness in component["harnesses"]:
                destination = component["outputs"][harness]
                if component["kind"] == "hook" and not destination.startswith("."):
                    destination = "." + harness + "/" + destination
                installed = root / destination
                if not installed.is_file() or installed.read_bytes() != (root / component["source"]).read_bytes():
                    raise ValueError("installed policy/runtime resource drift: " + destination)
                checked += 1
        elif component["kind"] == "config" and not component.get("distribution_only"):
            records = json.loads((root / component["source"]).read_text())["entries"]
            for harness in component["harnesses"]:
                installed = root / component["destinations"][harness]
                document = json.loads(installed.read_text()) if installed.is_file() else {}
                for record in records:
                    value = configuration.read(document, record)
                    matches = (sum(configuration.same(item, record["value"]) for item in value)
                               if record["mode"] == "entry" and value is not configuration.MISSING
                               else int(configuration.same(value, record["value"])))
                    if matches != 1:
                        raise ValueError("native setup entry drift: " + str(installed) + " " + record["id"])
                    checked += 1
    return checked


def self_paths(manifest):
    selection = manifest["self_application"]
    paths = []
    for component in selected_components(manifest, selection["domains"]):
        if component["kind"] == "skill" and component["scope"] == "project":
            for harness in component["harnesses"]:
                if selection[harness] == "direct":
                    paths.append((".claude/skills/" if harness == "claude" else ".agents/skills/") + component["name"])
        elif component["kind"] == "rule":
            name = Path(component["source"]).name
            paths.append(".rpi/rules/" + name)
            if component["mapping"]["mode"] == "conditional":
                paths.append(".claude/rules/" + name)
        elif component["kind"] in ("hook", "resource") and component["scope"] == "project":
            for harness in component["harnesses"]:
                destination = component["outputs"][harness]
                if component["kind"] == "hook" and not destination.startswith("."):
                    destination = "." + harness + "/" + destination
                paths.append(destination)
        elif component["kind"] == "config" and not component.get("distribution_only"):
            paths.extend(component["destinations"].values())
    return sorted(set(paths))


def load_sibling(name):
    spec = importlib.util.spec_from_file_location(name.replace("-", "_"), Path(__file__).with_name(name + ".py"))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def blocked_fix(error):
    """Corrective hint for a top-level failure. An unrepresentable path is a
    runtime encoding fault, so it must not send the owner to edit healthy source."""
    if getattr(error, "fix", None):
        return error.fix  # The failure site knows the exact repair.
    if isinstance(error, UnicodeError):
        return ("a path or name cannot be represented in this runtime's "
                f"{sys.getfilesystemencoding()} encoding; rerun under a UTF-8 locale, for example "
                "LC_ALL=C.UTF-8 or PYTHONUTF8=1. The candidate source is not at fault")
    return ("correct templates/distribution.json or its declared sources; "
            "rerun python3 templates/scripts/rpi-distribution.py validate")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("validate", "render", "check-generated", "check-native", "check-local-skills", "check-self", "self-paths", "counts", "plan", "apply", "check", "rollback", "detach", "diagnose"))
    parser.add_argument("--source", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument("--output", type=Path)
    # Default: both for install/render; an update keeps the recorded harnesses.
    parser.add_argument("--harness", choices=("both", *HARNESSES), default=None)
    parser.add_argument("--domain", action="append", default=None)
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--skill-dir", type=Path, action="append")
    parser.add_argument("--target", type=Path)
    parser.add_argument("--plan", type=Path)
    parser.add_argument("--journal", type=Path)
    parser.add_argument("--action", choices=("install", "update", "detach"), default="install")
    parser.add_argument("--route", choices=("direct", "plugin"), default=None)
    parser.add_argument("--scope", choices=("project", "user"), default="project")
    parser.add_argument("--state-root", type=Path)
    parser.add_argument("--claude-skill-root", type=Path)
    parser.add_argument("--codex-skill-root", type=Path)
    parser.add_argument("--legacy-base")
    parser.add_argument("--allow-capabilities", action="append", default=[])
    parser.add_argument("--fail-after", type=int, help=argparse.SUPPRESS)
    parser.add_argument("--fail-after-rename", type=int, help=argparse.SUPPRESS)
    sys.dont_write_bytecode = True  # Read-only dispatch must not create source caches.
    diagnostics = load_sibling("rpi-diagnostics")
    diagnostics.add_arguments(parser)
    args = parser.parse_args()
    if args.harness is None and args.command not in ("plan", "check", "detach"):
        args.harness = "both"
    try:
        if args.command == "diagnose":
            if args.target is None:
                raise ValueError("diagnose requires an explicit --target")
            return diagnostics.cli(args)
        if args.command in ("plan", "apply", "check", "rollback", "detach"):
            lifecycle = load_sibling("rpi-lifecycle")
            try:
                return lifecycle.cli(sys.modules[__name__], args)
            except lifecycle.TargetSettingsError as error:
                rerun = shlex.join([sys.executable, str(Path(__file__).resolve()), *sys.argv[1:]])
                print(f"BLOCKED / WHY: {error} / FIX: repair the JSON object in {error.path}, preserving owner settings; rerun {rerun}", file=sys.stderr)
                return 1
            except lifecycle.Conflict as error:
                print(json.dumps({"status": "conflict", "reason": str(error), "fix": lifecycle.blocked_hint(args, str(error), error.fix)}))
                return 2
        source = args.source.resolve()
        manifest = load_manifest(source)
        if args.command == "counts":
            print(json.dumps(counts(manifest), sort_keys=True))
            return 0
        if args.command == "self-paths":
            print("\n".join(self_paths(manifest)))
            return 0
        if args.command == "check-local-skills":
            excluded = () if args.skill_dir else {c["name"] for c in manifest["components"] if c["kind"] == "skill"}
            inspected = check_local_skills(args.skill_dir or [source / ".claude/skills", source / ".agents/skills"], excluded)
            if args.skill_dir and not inspected:
                raise ValueError("zero local skills inspected in the supplied directories")
            for harness, names in manifest["self_application"].get("local_extensions", {}).items():
                for name in names:
                    directory = source / (".claude/skills" if harness == "claude" else ".agents/skills") / name
                    if not (directory / "SKILL.md").is_file():
                        raise ValueError("missing declared local extension: " + str(directory))
            print(f"Validated {inspected} local extension skills; no source bytes changed")
            return 0
        tree = render_tree(source, HARNESSES if args.harness == "both" else (args.harness,), args.domain)
        output = args.output or source / "generated"
        if args.command == "render":
            write_tree(tree, output)
        elif args.command == "check-generated":
            check_tree(tree, output)
        elif args.command == "check-native":
            print(f"Validated {check_native(tree)} native metadata documents with YAML")
        elif args.command == "check-self":
            print(f"Validated {check_self(source, manifest)} self-applied skill files")
        print(json.dumps({"checked_components": len(manifest["components"]), "files": len(tree), "counts": counts(manifest), "managed_root_bytes": {h: len(tree[h + '/AGENTS.md']) for h in HARNESSES if h + '/AGENTS.md' in tree}}, sort_keys=True))
        return 0
    except (OSError, ValueError, KeyError, TypeError) as error:
        print(f"BLOCKED / WHY: {error} / FIX: {blocked_fix(error)}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
